### ISSUE TITLE
[1.16] Crash on startup

### ISSUE THREAD

**Issue by Weedoof** [SteveKunG/Indicatia#28] opened 2021-03-19 04:54 UTC
As the title. Loading indicatia on any forge version more recent than 36.0.48 (inclusive) causes forge to crash.

It's listed in the crash report, but I'm using the most recent version of Architectury and Indicatia at the time of writing, version 1.9.134 and 4.0.4, respectively. Also using Stevekung's lib 4.0.4, as mentioned in #27. 

[crash-2021-03-19_00.51.24-client.txt](https://github.com/SteveKunG/Indicatia/files/6168700/crash-2021-03-19_00.51.24-client.txt)

**Comment by SteveKunG** [comment] 2021-03-31 09:08
This is caused by forge changing their renderArmor method name, This was fixed in architectury version. I'd recommended to use architectury instead.

You can get it here : https://www.curseforge.com/minecraft/mc-mods/indicatia/files/3253918

**Closed as completed by SteveKunG** 2021-03-31 09:08 UTC

**Comment by Weedoof** [comment] 2021-04-02 19:47
What do you mean? I have architectury installed as well if that's what you mean.

**Comment by SteveKunG** [comment] 2021-04-03 02:52
Oh sorry I was confused, Current Indicatia 4.0.4 and SteveKunG's Lib will not work because forge change mapping to use mojmap.

You need Indicatia 4.1.1, SteveKunG's Lib 4.1.1 and Architectury API 1.8.131 or above to make it work.

**Comment by Weedoof** [comment] 2021-04-03 18:32
Ah, all right. Works fine now, thank you!
