### ISSUE TITLE
Game crashes when pressing F4

### ISSUE THREAD

**Issue by MYSTRAVIL** [SteveKunG/Indicatia#3] opened 2020-03-28 23:11 UTC
[crash-2020-03-29_00.08.45-client.txt](https://github.com/SteveKunG/Indicatia/files/4398036/crash-2020-03-29_00.08.45-client.txt)
[latest.log](https://github.com/SteveKunG/Indicatia/files/4398037/latest.log)

**Comment by Uma4-Chan** [comment] 2020-03-31 17:34
Yea, having the same problem

**Comment by SteveKunG** [comment] 2020-03-31 18:07
~~I don't know exactly why it crashed, When you just press F4 or going in the other menu?~~

OK, That's caused by bad upload script -.-

**Comment by SteveKunG** [comment] 2020-03-31 23:08
Fixed in 2.0.1 and 3.0.1.

**Closed as completed by SteveKunG** 2020-03-31 23:08 UTC

**Comment by Ouack23** [comment] 2020-04-12 17:37
Hello, 
I got the Rendering Screen issue with 1.15.2-3.0.1 when pressing F4.
https://pastebin.com/trKSU2c0
I know some of my mods aren't up to date, I'll try updating them to see what's up.

**Edit: Fixed after installing MixinBootstrap** : https://github.com/SteveKunG/MixinBootstrap/releases/download/1.0.3/MixinBootstrap-1.0.3.jar
